[package]
name = "sos"
version = "0.1.0"
edition = "2021"
include = ["**/*.rs", "Cargo.toml"]

[profile.dev]
panic = "abort"


[profile.release]
panic = "abort"

[[bin]]
name = "sos"
test = false
bench = false

[dependencies]
bootloader = "0.9"
