[package]
name = "sos2"
version = "0.1.0"
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "sos2"
test = false
bench = false

[dependencies]
bootloader = "0.9"
